import { Sen } from "next/font/google";
import "./globals.css";
//components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeProvider from "@/components/ThemeProvider";

//Them provider


const josef = Sen({ 
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  display: "swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body className={josef.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
          >
        <Header></Header>
        {children}
        <Footer></Footer>
        </ThemeProvider>
        </body>
    </html>
  );
}
